### ISSUE TITLE
Dataset release information and timeline

### ISSUE THREAD

**Issue by karmarv** [tackgeun/CausalityInTrafficAccident#1]
Do you plan to release this dataset to public ! 
If yes then when would that be. I would like to try this out.

**Comment by tackgeun** [comment]
Sorry for the late answer. I'm just returning from CVPR submission.
I will release the dataset before the end of this year.

**Comment by chowkamlee81** [comment]
@tackgeun 
Can you kindly release the dataset which is helpful for community

**Comment by tackgeun** [comment]
I've uploaded the dataset (refer the details of dataset page) and its action recognition baseline.
Action localization baseline will be available before the end of the June.

Thanks.
