### ISSUE TITLE
Metainformation not coinciding with youtube videos.

### ISSUE THREAD

**Issue by chowkamlee81** [tackgeun/CausalityInTrafficAccident#3]
In the annotation pkl file 

('v_Mfru8T-bHEE', 3.12, 26.16),  i.e (Youtube clip ID, start time in Youtube clip, end time in Youtube clip)
('Control Loss', 11.128526999999998, 13.180663, 2),n  i.e  (cause semantic label, cause start time, cause end time, cause semantic label index)
 ('Collision w/ Road Obstacle', 13.180663, 15.272419, 20)  i.e (effect semantic label, effect start time, effect end time, effect semantic label index)

In the video https://www.youtube.com/watch?v=Mfru8T-bHEE, in youtube video is of duration 0.00 to 10.52 minutes but start and endtime is even greater than the youtube.
This is not the only one video, but for rest of the annotations and videos is same.

Ami missing anything? Kindly help and do the needful

**Comment by chowkamlee81** [comment]
@tackgeun 
I got the info. You have mentioned in seconds and i got into confusion. Now works.

**Comment by tackgeun** [comment]
I've also updated this issue on the details of the dataset. 
Thank you for referring to the problem.
